=== KeresztesIulia/ULA7Z2_XMLGyak/ULA7Z2_1018/fesztivál_ULA7Z2/XMLSchemaULA7Z2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- egyszerű típusok -->

<xs:element name="fellépő_név" type="xs:string"/>
<xs:element name="ország" type="xs:string"/>
<xs:element name="díj" type="xs:string"/>

<xs:element name="fesztivál_név" type="xs:string"/>
<xs:element name="helyszín" type="xs:string"/>
<xs:element name="év" type="xs:int"/>

<xs:element name="bár_név" type="xs:string"/>
<xs:element name="ital" type="xs:string"/>
<xs:element name="cég" type="xs:string"/>

<xs:element name="alkalmazott_név" type="xs:string"/>
<xs:element name="műszak" type="xs:string"/>
<xs:element name="fizetés" type="xs:string"/>

<xs:element name="tulajdonos_név" type="xs:string"/>
<xs:element name="adószám" type="xs:string"/>
<xs:element name="alapítás" type="xs:string"/>
<xs:element name="bevétel" type="xs:string"/>

<xs:element name="résztvevő_név" type="xs:string"/>
<xs:element name="diákigazolvány" type="xs:string"/>
<xs:element name="település" type="xs:string"/>
<xs:element name="utca" type="xs:string"/> 
<xs:element name="házszám" type="xs:string"/>

<xs:element name="kérdező" type="xs:string"/>

<xs:element name="nyelv" type="xs:string"/>
<xs:element name="szint" type="szintTípus"/>

<xs:simpleType name="szintTípus">
    <xs:restriction base="xs:string">
        <xs:pattern value="[A-C][1-2]"/>
    </xs:restriction>
</xs:simpleType>

<!-- komplex típusok -->
<xs:element name="fellépő" type="fellépőTípus" />
<xs:complexType name="fellépőTípus">
    <xs:sequence>
        <xs:element ref="fellépő_név" />
        <xs:element ref="ország" />
        <xs:element ref="díj" />
    </xs:sequence>
    <xs:attribute ref="FEL_ID"/>
    <xs:attribute ref="FEL_FESZ"/>
</xs:complexType>

<xs:element name="fesztivál" type="fesztiválTípus" />
<xs:complexType name="fesztiválTípus">
    <xs:sequence>
        <xs:element ref="fesztivál_név" />
        <xs:element ref="helyszín" />
        <xs:element ref="év" />
    </xs:sequence>
    <xs:attribute ref="FESZ_ID"/>
</xs:complexType>

<xs:element name="bár" type="bárTípus" />
<xs:complexType name="bárTípus">
    <xs:sequence>
        <xs:element ref="bár_név" />
        <xs:element ref="ital" minOccurs="1" maxOccurs="unbounded" />
        <xs:element ref="cég" />
    </xs:sequence>
    <xs:attribute ref="B_ID"/>
    <xs:attribute ref="FESZ_B"/>
</xs:complexType>

<xs:element name="alkalmazott" type="alkalmazottTípus" />
<xs:complexType name="alkalmazottTípus">
    <xs:sequence>
        <xs:element ref="alkalmazott_név" />
        <xs:element ref="műszak" minOccurs="1" maxOccurs="unbounded" />
        <xs:element ref="fizetés" />
    </xs:sequence>
    <xs:attribute ref="A_ID"/>
    <xs:attribute ref="B_A"/>
</xs:complexType>

<xs:element name="tulajdonos" type="tulajdonosTípus" />
<xs:complexType name="tulajdonosTípus">
    <xs:sequence>
        <xs:element ref="tulajdonos_név" />
        <xs:element ref="adószám" />
        <xs:element ref="alapítás" />
        <xs:element ref="bevétel" />
    </xs:sequence>
    <xs:attribute ref="T_ID"/>
    <xs:attribute ref="FESZ_T"/>
</xs:complexType>

<xs:element name="lakcím" type="lakcímTípus" />
<xs:complexType name="lakcímTípus">
    <xs:sequence>
        <xs:element ref="település" />
        <xs:element ref="utca" />
        <xs:element ref="házszám" />
    </xs:sequence>
</xs:complexType>

<xs:element name="résztvevő" type="résztvevőTípus" />
<xs:complexType name="résztvevőTípus">
    <xs:sequence>
        <xs:element ref="résztvevő_név" />
        <xs:element ref="diákigazolvány" minOccurs="0" maxOccurs="1" />
        <xs:element ref="lakcím" />
    </xs:sequence>
    <xs:attribute ref="R_ID"/>
    <xs:attribute ref="FESZ_R"/>
</xs:complexType>

<xs:element name="közvélemény" type="közvéleményTípus" />
<xs:complexType name="közvéleményTípus">
    <xs:sequence>
        <xs:element ref="kérdező" />
    </xs:sequence>
    <xs:attribute ref="K_ID"/>
    <xs:attribute ref="K_R"/>
    <xs:attribute ref="K_NY"/>
</xs:complexType>

<xs:element name="nyelvtudás" type="nyelvtudásTípus" />
<xs:complexType name="nyelvtudásTípus">
    <xs:sequence>
        <xs:element ref="nyelv" />
        <xs:element ref="szint" />
    </xs:sequence>
    <xs:attribute ref="NY_ID"/>
</xs:complexType>

<!-- gyökérelem refek -->
<xs:element name="Fesztivál_ULA7Z2">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="fesztivál" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="fellépő" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="bár" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="alkalmazott" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="tulajdonos" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="résztvevő" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="nyelvtudás" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="közvélemény" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <!-- elsődleges kulcsok -->
    <xs:key name="fellépőID">
        <xs:selector xpath="fellépő" />
        <xs:field xpath="@FEL_ID" />
    </xs:key>
    <xs:key name="fesztiválID">
        <xs:selector xpath="fesztivál" />
        <xs:field xpath="@FESZ_ID" />
    </xs:key>
    <xs:key name="bárID">
        <xs:selector xpath="bár" />
        <xs:field xpath="@B_ID" />
    </xs:key>
    <xs:key name="alkalmazottID">
        <xs:selector xpath="alkalmazott" />
        <xs:field xpath="@A_ID" />
    </xs:key>
    <xs:key name="tulajdonosID">
        <xs:selector xpath="tulajdonos" />
        <xs:field xpath="@T_ID" />
    </xs:key>
    <xs:key name="résztvevőID">
        <xs:selector xpath="résztvevő" />
        <xs:field xpath="@R_ID" />
    </xs:key>
    <xs:key name="nyelvtudásID">
        <xs:selector xpath="nyelvtudás" />
        <xs:field xpath="@NY_ID" />
    </xs:key>
    <xs:key name="közvéleményID">
        <xs:selector xpath="közvélemény" />
        <xs:field xpath="@K_ID" />
    </xs:key>

    <!-- idegenkulcsok -->
    <xs:keyref name="fel_feszREF" refer="fesztiválID">
        <xs:selector xpath="fellépő" />
        <xs:field xpath="@FEL_FESZ" />
    </xs:keyref>
    <xs:keyref name="fesz_bárREF" refer="fesztiválID">
        <xs:selector xpath="bár" />
        <xs:field xpath="@FESZ_B" />
    </xs:keyref>
    <xs:keyref name="bár_alkREF" refer="bárID">
        <xs:selector xpath="alkalmazott" />
        <xs:field xpath="@B_A" />
    </xs:keyref>
    <xs:keyref name="fesz_tulREF" refer="fesztiválID">
        <xs:selector xpath="tulajdonos" />
        <xs:field xpath="@FESZ_T" />
    </xs:keyref>
    <xs:keyref name="fesz_részREF" refer="fesztiválID">
        <xs:selector xpath="résztvevő" />
        <xs:field xpath="@FESZ_R" />
    </xs:keyref>
    <xs:keyref name="köz_részREF" refer="résztvevőID">
        <xs:selector xpath="közvélemény" />
        <xs:field xpath="@K_R" />
    </xs:keyref>
    <xs:keyref name="köz_nyelvREF" refer="nyelvtudásID">
        <xs:selector xpath="közvélemény" />
        <xs:field xpath="@K_NY" />
    </xs:keyref>
</xs:element>

<!-- elsődleges kulcsok -->
<xs:attribute name="FEL_ID" type="xs:ID"/>
<xs:attribute name="FESZ_ID" type="xs:ID" />
<xs:attribute name="B_ID" type="xs:ID"/>
<xs:attribute name="A_ID" type="xs:ID"/>
<xs:attribute name="T_ID" type="xs:ID"/>
<xs:attribute name="R_ID" type="xs:ID"/>
<xs:attribute name="NY_ID" type="xs:ID"/>
<xs:attribute name="K_ID" type="xs:ID"/>


<!-- idegen kulcsok -->
<xs:attribute name="FEL_FESZ" type="xs:IDREF"/>
<xs:attribute name="FESZ_B" type="xs:IDREF"/>
<xs:attribute name="B_A" type="xs:IDREF"/>
<xs:attribute name="FESZ_T" type="xs:IDREF"/>
<xs:attribute name="FESZ_R" type="xs:IDREF"/>
<xs:attribute name="K_R" type="xs:IDREF"/>
<xs:attribute name="K_NY" type="xs:IDREF"/>

</xs:schema>

=== KeresztesIulia/ULA7Z2_XMLGyak/ULA7Z2_1018/fesztivál_ULA7Z2/XMLULA7Z2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Fesztivál_ULA7Z2 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaULA7Z2.xsd">
    <!-- Fesztiválok -->
    <fesztivál FESZ_ID="FESZ01">
        <fesztivál_név>Sziget-fesztivál</fesztivál_név>
        <helyszín>Budapest</helyszín>
        <év>2024</év>
    </fesztivál>
    <fesztivál FESZ_ID="FESZ02">
        <fesztivál_név>SUN fesztivál</fesztivál_név>
        <helyszín>Csobánkapuszta</helyszín>
        <év>2023</év>
    </fesztivál>

    <!-- Fellépők -->
    <fellépő FEL_ID="FEL01" FEL_FESZ="FESZ01">
        <fellépő_név>ASA MASA</fellépő_név>
        <ország>Finnország</ország>
        <díj>450000</díj>
    </fellépő>
    <fellépő FEL_ID="FEL02" FEL_FESZ="FESZ02">
        <fellépő_név>Ananda Shanti</fellépő_név>
        <ország>Németország</ország>
        <díj>500000</díj>
    </fellépő>

    <!-- Bárok -->
    <bár B_ID="B01" FESZ_B="FESZ01">
        <bár_név>Boutiq'Bar</bár_név>
        <ital>whiskey</ital>
        <ital>koktél</ital>
        <ital>tequila</ital>
        <cég>Metaxa</cég>
    </bár>
    <bár B_ID="B02" FESZ_B="FESZ02">
        <bár_név>Retro Pub</bár_név>
        <ital>sör</ital>
        <ital>pálinka</ital>
        <cég>Heineken</cég>
    </bár>

    <!-- Alkalmazottak -->
    <alkalmazott A_ID="A01" B_A="B01">
        <alkalmazott_név>Pálinkás Elemér</alkalmazott_név>
        <műszak>nappali</műszak>
        <fizetés>250000</fizetés>
    </alkalmazott>
    <alkalmazott A_ID="A02" B_A="B02">
        <alkalmazott_név>Áronkané Amália</alkalmazott_név>
        <műszak>esti</műszak>
        <fizetés>400000</fizetés>
    </alkalmazott>

    <!-- Tulajdonosok -->
    <tulajdonos T_ID="T01" FESZ_T="FESZ01">
        <tulajdonos_név>Gerendai Károly</tulajdonos_név>
        <adószám>24150604-2-43</adószám>
        <alapítás>1993</alapítás>
        <bevétel>2000000</bevétel>
    </tulajdonos>
    <tulajdonos T_ID="T02" FESZ_T="FESZ02">
        <tulajdonos_név>Mély Mosoly Alapítvány</tulajdonos_név>
        <adószám>HU 18167838</adószám>
        <alapítás>1999</alapítás>
        <bevétel>1500000</bevétel>
    </tulajdonos>

    <!-- Résztvevők -->
    <résztvevő R_ID="R01" FESZ_R="FESZ01">
        <résztvevő_név>Cserei Ágnes</résztvevő_név>
        <diákigazolvány>26448557956</diákigazolvány>
        <lakcím>
            <település>Budapest</település>
            <utca>Láng Endre u.</utca>
            <házszám>14</házszám>
        </lakcím>
    </résztvevő>
    <résztvevő R_ID="R02" FESZ_R="FESZ02">
        <résztvevő_név>Kalapos Márton</résztvevő_név>
        <lakcím>
            <település>Debrecen</település>
            <utca>Tas u.</utca>
            <házszám>6</házszám>
        </lakcím>
    </résztvevő>

    <!-- Nyelvtudás -->
    <nyelvtudás NY_ID="EN_A1">
        <nyelv>angol</nyelv>
        <szint>A1</szint>
    </nyelvtudás>
    <nyelvtudás NY_ID="EN_A2">
        <nyelv>angol</nyelv>
        <szint>A2</szint>
    </nyelvtudás> 
    <nyelvtudás NY_ID="EN_B1">
        <nyelv>angol</nyelv>
        <szint>B1</szint>
    </nyelvtudás>  
    <nyelvtudás NY_ID="EN_B2">
        <nyelv>angol</nyelv>
        <szint>B2</szint>
    </nyelvtudás>
    <nyelvtudás NY_ID="EN_C1">
        <nyelv>angol</nyelv>
        <szint>C1</szint>
    </nyelvtudás> 
    <nyelvtudás NY_ID="EN_C2">
        <nyelv>angol</nyelv>
        <szint>C2</szint>
    </nyelvtudás>

    <!-- Közvélemények -->
    <közvélemény K_ID="K01" K_R="R01" K_NY="EN_B1">
        <kérdező>Ólom Iván János</kérdező>
    </közvélemény>
    <közvélemény K_ID="K02" K_R="R02" K_NY="EN_C2">
        <kérdező>Mérai Kevin</kérdező>
    </közvélemény>
</Fesztivál_ULA7Z2>
